# Generated by Django 4.1.4 on 2023-01-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_of', models.CharField(choices=[('IT', 'IT'), ('ACCOUNTS', 'ACCOUNTS'), ('SALES', 'SALES')], default='IT', max_length=225)),
                ('Role_is', models.CharField(choices=[('DEVELOP', 'DEVELOPER'), ('ACCOUNT', 'ACCOUNTANT'), ('MARKET', 'MARKETING')], default='DEVELOP', max_length=225)),
                ('python', models.BooleanField(default=True, verbose_name='python')),
                ('C', models.BooleanField(default=True, verbose_name='C++')),
                ('Account', models.BooleanField(default=False, verbose_name='Accountancy')),
                ('Product', models.BooleanField(default=False, verbose_name=' Product_Awareness')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
