# Generated by Django 4.1.4 on 2023-01-10 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_of', models.CharField(choices=[('IT', 'IT'), ('ACCOUNTS', 'ACCOUNTS'), ('SALES', 'SALES')], default='IT', max_length=225)),
                ('Role_is', models.CharField(choices=[('DEVELOP', 'DEVELOPER'), ('ACCOUNT', 'ACCOUNTANT'), ('MARKET', 'MARKETING')], default='DEVELOP', max_length=225)),
                ('python', models.BooleanField(default=True, verbose_name='python')),
                ('C', models.BooleanField(default=True, verbose_name='C++')),
                ('Account', models.BooleanField(default=False, verbose_name='Accountancy')),
                ('Product', models.BooleanField(default=False, verbose_name=' Product_Awareness')),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='Account',
        ),
        migrations.RemoveField(
            model_name='department',
            name='C',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Department_of',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Role_is',
        ),
        migrations.RemoveField(
            model_name='department',
            name='python',
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.department')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quiz.department')),
                ('Role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quiz.role')),
            ],
        ),
    ]
