# Generated by Django 4.1.4 on 2022-12-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_remove_login_login_alter_login_login_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Login_id',
            new_name='username',
        ),
    ]
