# Generated by Django 4.1.4 on 2023-01-11 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_alter_person_name_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.department'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('Role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.department')),
            ],
        ),
    ]
