# Generated by Django 4.1.4 on 2023-01-12 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_alter_role_department_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='Role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.role'),
        ),
    ]
