# Generated by Django 4.1.4 on 2022-12-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_rename_login_id_login_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Password',
            new_name='password',
        ),
    ]
