# Generated by Django 4.1.4 on 2023-01-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_alter_topic_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='Role',
            new_name='role',
        ),
    ]
