# Generated by Django 4.1.4 on 2023-01-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_rename_department_role_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=55, null=True)),
                ('role', models.CharField(blank=True, max_length=55, null=True)),
                ('topic', models.CharField(blank=True, max_length=55, null=True)),
                ('question', models.CharField(max_length=200, null=True)),
                ('answeroption', models.CharField(blank=True, max_length=55, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Role',
        ),
        migrations.DeleteModel(
            name='QuesModel',
        ),
        migrations.RemoveField(
            model_name='role',
            name='department',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='role',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
