# Generated by Django 3.2.16 on 2023-01-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0004_hrlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrlogin',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='hrlogin',
            name='username1',
        ),
        migrations.AddField(
            model_name='hrlogin',
            name='login_input',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hrlogin',
            name='login_ouput',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
