# Generated by Django 3.2.16 on 2023-02-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
