# Generated by Django 3.2.16 on 2023-02-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0002_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
