# Generated by Django 3.2.16 on 2023-02-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0002_auto_20230215_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
