# Generated by Django 3.2.16 on 2023-02-07 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0003_auto_20230207_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitudetest.role')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitudetest.department')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitudetest.test')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitudetest.topic')),
            ],
        ),
    ]
