# Generated by Django 3.2.16 on 2023-02-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0005_account_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
