# Generated by Django 3.2.16 on 2023-01-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0006_auto_20230107_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrlogin',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='hrlogin',
            name='user',
        ),
        migrations.AddField(
            model_name='hrlogin',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hrlogin',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
