# Generated by Django 3.2.16 on 2023-01-07 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aptitudetest', '0007_auto_20230107_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrlogin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='hrlogin',
            name='username',
        ),
        migrations.AddField(
            model_name='hrlogin',
            name='auth_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hrlogin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hrlogin',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hrlogin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
