# Generated by Django 3.2.16 on 2023-01-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0008_auto_20230107_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
