# Generated by Django 3.2.16 on 2023-01-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0009_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Department_of',
            field=models.CharField(choices=[('IT', 'IT'), ('ACCOUNTS', 'ACCOUNTS'), ('SALES', 'SALES')], default='IT', max_length=225),
        ),
    ]
