# Generated by Django 3.2.16 on 2023-01-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0010_department_department_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Choose_Field',
            field=models.CharField(blank=True, choices=[('DEVELOPER', 'DEVELOPER')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='Department_of',
            field=models.CharField(choices=[('IT', 'IT'), ('ACCOUNTS', 'ACCOUNTS'), ('SALES', 'SALES')], max_length=225),
        ),
    ]
