# Generated by Django 3.2.16 on 2023-01-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0011_auto_20230111_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Domin',
            field=models.CharField(choices=[('PYTHON', 'python')], default='PYTHON', max_length=225),
        ),
        migrations.AddField(
            model_name='department',
            name='MARKET',
            field=models.CharField(choices=[('CLIENT AND SUPPORT', 'CLIENT AND SUPPORT')], default='CLIENT AND SUPPORT', max_length=255),
        ),
        migrations.AddField(
            model_name='department',
            name='choose',
            field=models.CharField(choices=[('ACCOUNTANT', 'ACCOUNTANT')], default='ACCOUNTANT', max_length=225),
        ),
        migrations.AddField(
            model_name='department',
            name='in_accountant',
            field=models.CharField(choices=[('ACCOUNTANCY', 'ACCOUNTANCY')], default='ACCOUNTANCY', max_length=225),
        ),
        migrations.AddField(
            model_name='department',
            name='saling',
            field=models.CharField(choices=[('marketing', 'MARKETING')], default='marketing', max_length=225),
        ),
        migrations.AlterField(
            model_name='department',
            name='Choose_Field',
            field=models.CharField(choices=[('DEVELOPER', 'DEVELOPER')], default=[('PYTHON', 'python')], max_length=225),
        ),
    ]
