# Generated by Django 3.2.16 on 2023-01-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0012_auto_20230111_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='MARKET',
        ),
        migrations.RemoveField(
            model_name='department',
            name='choose',
        ),
        migrations.RemoveField(
            model_name='department',
            name='in_accountant',
        ),
        migrations.RemoveField(
            model_name='department',
            name='saling',
        ),
        migrations.AddField(
            model_name='department',
            name='ACCOUNTANT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='ACCOUNTS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='MARKETING',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='SALES',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='Choose_Field',
            field=models.CharField(choices=[('DEVELOPER', 'DEVELOPER'), ('ACCOUNTANT', 'ACCOUNTANT'), ('MARKETING', 'MARKETING')], default=[('PYTHON', 'python'), ('ACCOUNTANCY', 'ACCOUNTANCY'), ('CLIENT AND SUPPORT', 'CLIENT AND SUPPORT')], max_length=225),
        ),
        migrations.AlterField(
            model_name='department',
            name='Domin',
            field=models.CharField(choices=[('PYTHON', 'python'), ('ACCOUNTANCY', 'ACCOUNTANCY'), ('CLIENT AND SUPPORT', 'CLIENT AND SUPPORT')], default='PYTHON', max_length=225),
        ),
    ]
