# Generated by Django 3.2.16 on 2023-01-11 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aptitudetest', '0013_auto_20230111_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='ACCOUNTANT',
        ),
        migrations.RemoveField(
            model_name='department',
            name='ACCOUNTS',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Choose_Field',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Department_of',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Domin',
        ),
        migrations.RemoveField(
            model_name='department',
            name='MARKETING',
        ),
        migrations.RemoveField(
            model_name='department',
            name='SALES',
        ),
        migrations.AddField(
            model_name='department',
            name='auth_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
