# Generated by Django 3.2.16 on 2023-01-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0014_auto_20230111_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.AddField(
            model_name='department',
            name='ACCOUNTANT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='ACCOUNTS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='Choose_Field',
            field=models.CharField(choices=[('DEVELOPER', 'DEVELOPER'), ('ACCOUNTANT', 'ACCOUNTANT'), ('MARKETING', 'MARKETING')], default=[('PYTHON', 'python'), ('ACCOUNTANCY', 'ACCOUNTANCY'), ('CLIENT AND SUPPORT', 'CLIENT AND SUPPORT')], max_length=225),
        ),
        migrations.AddField(
            model_name='department',
            name='Department_of',
            field=models.CharField(choices=[('IT', 'IT'), ('ACCOUNTS', 'ACCOUNTS'), ('SALES', 'SALES')], default='IT', max_length=225),
        ),
        migrations.AddField(
            model_name='department',
            name='Domin',
            field=models.CharField(choices=[('PYTHON', 'python'), ('ACCOUNTANCY', 'ACCOUNTANCY'), ('CLIENT AND SUPPORT', 'CLIENT AND SUPPORT')], default='PYTHON', max_length=225),
        ),
        migrations.AddField(
            model_name='department',
            name='MARKETING',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='SALES',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
