# Generated by Django 3.2.16 on 2023-01-11 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0015_auto_20230111_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='ACCOUNTANT',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Choose_Field',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Department_of',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Domin',
        ),
        migrations.RemoveField(
            model_name='department',
            name='MARKETING',
        ),
        migrations.AddField(
            model_name='department',
            name='IT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEVELOPER', models.CharField(blank=True, max_length=50, null=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptitudetest.department')),
            ],
        ),
    ]
