# Generated by Django 3.2.16 on 2023-01-11 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0016_auto_20230111_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='ACCOUNTS',
        ),
        migrations.RemoveField(
            model_name='department',
            name='IT',
        ),
        migrations.RemoveField(
            model_name='department',
            name='SALES',
        ),
        migrations.RemoveField(
            model_name='role',
            name='DEVELOPER',
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitudetest.department'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('Role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitudetest.role')),
            ],
        ),
    ]
