# Generated by Django 3.2.16 on 2023-01-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0017_auto_20230111_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testaccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answeroption', models.CharField(blank=True, max_length=50, null=True)),
                ('a', models.CharField(blank=True, max_length=50, null=True)),
                ('b', models.CharField(blank=True, max_length=50, null=True)),
                ('c', models.CharField(blank=True, max_length=50, null=True)),
                ('d', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testsales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answeroption', models.CharField(blank=True, max_length=50, null=True)),
                ('a', models.CharField(blank=True, max_length=50, null=True)),
                ('b', models.CharField(blank=True, max_length=50, null=True)),
                ('c', models.CharField(blank=True, max_length=50, null=True)),
                ('d', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
