# Generated by Django 3.2.16 on 2023-01-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0018_testaccounts_testsales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testaccounts',
            new_name='Testaccount',
        ),
        migrations.RenameModel(
            old_name='Testsales',
            new_name='Testsale',
        ),
    ]
