# Generated by Django 3.2.16 on 2023-01-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0019_auto_20230112_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Department',
            new_name='department',
        ),
    ]
