# Generated by Django 3.2.16 on 2023-01-14 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aptitudetest', '0020_rename_department_role_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptituteTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateTimeField()),
                ('ended_on', models.DateTimeField()),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate', to=settings.AUTH_USER_MODEL)),
                ('testqueestion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_question', to='aptitudetest.test')),
            ],
        ),
    ]
