# Generated by Django 3.2.16 on 2023-01-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0021_aptitutetest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testaccount',
        ),
        migrations.DeleteModel(
            name='Testsale',
        ),
        migrations.AddField(
            model_name='aptitutetest',
            name='question_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answeroption',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=200, null=True),
        ),
    ]
