# Generated by Django 3.2.16 on 2023-01-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudetest', '0022_auto_20230114_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answeroption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
